//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_ChangTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMon
    {
        public string MaNL { get; set; }
        public string MaMon { get; set; }
        public Nullable<int> SoLuongDaDung { get; set; }
    
        public virtual Mon Mon { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
